/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated.trades'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated.trades.index'
import { Route as AuthenticatedTradesNewRouteImport } from './routes/_authenticated.trades.new'
import { Route as AuthenticatedTradesTradeIdRouteImport } from './routes/_authenticated.trades.$tradeId'
import { Route as AuthenticatedTradesTradeIdIndexRouteImport } from './routes/_authenticated.trades.$tradeId.index'
import { Route as AuthenticatedTradesTradeIdEditRouteImport } from './routes/_authenticated.trades.$tradeId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTradesRoute,
  } as any)
const AuthenticatedTradesNewRoute = AuthenticatedTradesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTradesRoute,
} as any)
const AuthenticatedTradesTradeIdRoute =
  AuthenticatedTradesTradeIdRouteImport.update({
    id: '/$tradeId',
    path: '/$tradeId',
    getParentRoute: () => AuthenticatedTradesRoute,
  } as any)
const AuthenticatedTradesTradeIdIndexRoute =
  AuthenticatedTradesTradeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTradesTradeIdRoute,
  } as any)
const AuthenticatedTradesTradeIdEditRoute =
  AuthenticatedTradesTradeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTradesTradeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRouteWithChildren
  '/trades/new': typeof AuthenticatedTradesNewRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
  '/trades/$tradeId/edit': typeof AuthenticatedTradesTradeIdEditRoute
  '/trades/$tradeId/': typeof AuthenticatedTradesTradeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trades/new': typeof AuthenticatedTradesNewRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
  '/trades/$tradeId/edit': typeof AuthenticatedTradesTradeIdEditRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRouteWithChildren
  '/_authenticated/trades/$tradeId': typeof AuthenticatedTradesTradeIdRouteWithChildren
  '/_authenticated/trades/new': typeof AuthenticatedTradesNewRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
  '/_authenticated/trades/$tradeId/edit': typeof AuthenticatedTradesTradeIdEditRoute
  '/_authenticated/trades/$tradeId/': typeof AuthenticatedTradesTradeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/trades'
    | '/trades/$tradeId'
    | '/trades/new'
    | '/trades/'
    | '/trades/$tradeId/edit'
    | '/trades/$tradeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/trades/new'
    | '/trades'
    | '/trades/$tradeId/edit'
    | '/trades/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/trades'
    | '/_authenticated/trades/$tradeId'
    | '/_authenticated/trades/new'
    | '/_authenticated/trades/'
    | '/_authenticated/trades/$tradeId/edit'
    | '/_authenticated/trades/$tradeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/trades/new': {
      id: '/_authenticated/trades/new'
      path: '/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof AuthenticatedTradesNewRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/trades/$tradeId': {
      id: '/_authenticated/trades/$tradeId'
      path: '/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/trades/$tradeId/': {
      id: '/_authenticated/trades/$tradeId/'
      path: '/'
      fullPath: '/trades/$tradeId/'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdIndexRouteImport
      parentRoute: typeof AuthenticatedTradesTradeIdRoute
    }
    '/_authenticated/trades/$tradeId/edit': {
      id: '/_authenticated/trades/$tradeId/edit'
      path: '/edit'
      fullPath: '/trades/$tradeId/edit'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdEditRouteImport
      parentRoute: typeof AuthenticatedTradesTradeIdRoute
    }
  }
}

interface AuthenticatedTradesTradeIdRouteChildren {
  AuthenticatedTradesTradeIdEditRoute: typeof AuthenticatedTradesTradeIdEditRoute
  AuthenticatedTradesTradeIdIndexRoute: typeof AuthenticatedTradesTradeIdIndexRoute
}

const AuthenticatedTradesTradeIdRouteChildren: AuthenticatedTradesTradeIdRouteChildren =
  {
    AuthenticatedTradesTradeIdEditRoute: AuthenticatedTradesTradeIdEditRoute,
    AuthenticatedTradesTradeIdIndexRoute: AuthenticatedTradesTradeIdIndexRoute,
  }

const AuthenticatedTradesTradeIdRouteWithChildren =
  AuthenticatedTradesTradeIdRoute._addFileChildren(
    AuthenticatedTradesTradeIdRouteChildren,
  )

interface AuthenticatedTradesRouteChildren {
  AuthenticatedTradesTradeIdRoute: typeof AuthenticatedTradesTradeIdRouteWithChildren
  AuthenticatedTradesNewRoute: typeof AuthenticatedTradesNewRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedTradesRouteChildren: AuthenticatedTradesRouteChildren = {
  AuthenticatedTradesTradeIdRoute: AuthenticatedTradesTradeIdRouteWithChildren,
  AuthenticatedTradesNewRoute: AuthenticatedTradesNewRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedTradesRouteWithChildren =
  AuthenticatedTradesRoute._addFileChildren(AuthenticatedTradesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
